name: Update Notion Database

on:
  workflow_run:
    workflows: ['*'] # 모든 워크플로우 완료 시 실행
    types:
      - completed
  # 또는 특정 이벤트에 실행
  # push:
  #   branches: [main]

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Update Notion Database
        uses: actions/github-script@v6
        with:
          script: |
            const { Client } = require('@notionhq/client');

            const notion = new Client({
              auth: '${{ secrets.NOTION_TOKEN }}'
            });

            const databaseId = '${{ secrets.NOTION_DATABASE_ID }}';

            // 워크플로우 정보 수집
            const workflowName = context.workflow;
            const status = '${{ job.status }}' || 'unknown';
            const branch = context.ref.replace('refs/heads/', '');
            const commit = context.sha.substring(0, 7);

            try {
              await notion.pages.create({
                parent: { database_id: databaseId },
                properties: {
                  'Workflow': {
                    title: [{ text: { content: workflowName } }]
                  },
                  'Status': {
                    select: { name: status }
                  },
                  'Branch': {
                    rich_text: [{ text: { content: branch } }]
                  },
                  'Commit': {
                    rich_text: [{ text: { content: commit } }]
                  },
                  'Date': {
                    date: { start: new Date().toISOString() }
                  },
                  'Repository': {
                    rich_text: [{ text: { content: context.repo.repo } }]
                  }
                }
              });
              console.log('Successfully updated Notion database');
            } catch (error) {
              console.error('Error updating Notion:', error);
            }
